#%RAML 1.0
title: American Flights API
version: 1.0
#Simple demonstration of raml json schema.
#Using '!inclue' to reference external schema json files.

schemas:
  login: !include schemas/login.json
  assign: !include schemas/assign.json
  checkList: !include schemas/checkList.json
  byRoleId: !include schemas/byRoleId.json
  saveAssignAgent: !include schemas/saveAssignAgent.json

/userLogin:
  post:
    body:
      application/json:     
        schema: login
    responses:
      200:
        body:
          application/json: 
/searchResult:
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
/fields:
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
/summary:
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
/searchBy:
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
/checkList:
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
/assign:
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
/saveAssignAgent:
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
/getRemark:
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
/saveRemark:
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
/saveRejectReason:
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:        
/getRejectedRoleName:
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
/reactivateStatus:
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
/selectRecjectReason:
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
/progressFields:
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
/progressFilter:
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json: